name: "Send Email With SendGrid"
author: "meysam@licenseware.io"
description: "Using python library, send an email to SendGrid API"
branding:
  icon: "info"
  color: "green"
inputs:
  from-email:
    required: true
  to-email:
    required: true
  api-key:
    required: true
  subject:
    required: true
  markdown-body:
    required: true
  attachments:
    required: false
    description: "Space separated list of attachments"
  attachments-disposition:
    required: false
    description: "inline or attachment"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --api-key=${{ inputs.api-key }}
    - --from=${{ inputs.from-email }}
    - --to=${{ inputs.to-email }}
    - --subject=${{ inputs.subject }}
    - --markdown-body=${{ inputs.markdown-body }}
    - --attachments=${{ inputs.attachments }}
    - --attachments-disposition=${{ inputs.attachments-disposition }}
